### ISSUE TITLE
Could you give an example for converting Hyperts trainning model to PMML file?

### ISSUE THREAD

**Issue by mengzhizihu** [DataCanvasIO/HyperTS#100]
I need use the PMML file in java to predict, but I don't know how to convert model trainning by Hyperts to PMML file.
Could you give an example for converting Hyperts trainning model to PMML file?

**Comment by zhangxjohn** [comment]
Sorry, I do not know how to do it. You can learn how to conver a model trained by python, sklearn, or tensorflow to a PMML file. For example. `sklearn2pmml `package and so on.
