### ISSUE TITLE
max_trials 设置最大搜索次数

### ISSUE THREAD

**Issue by hello-the-vsworld** [DataCanvasIO/HyperTS#103]
最大搜索次数为数值100有意义吗？我的意思是库里包含的算法就几十种，搜索100次是不是没有意义啊，搜索次数最大等于算法最大个数是不是就行了。感谢解答

**Comment by zhangxjohn** [comment]
有意义，搜索中不止探索了不同的模型，还对每个模型的超参数组合进行了搜索，最终以获得最好模型的最好的超参数。

**Comment by hello-the-vsworld** [comment]
此过程是相当于寻找最优算法加之训练超参数，随着每个模型的超参数不同，是否还会变换选择算法，还是选择一种算法后，优化其参数？

**Comment by zhangxjohn** [comment]
算法和超参数都会变化。

**Comment by hello-the-vsworld** [comment]
好的，感谢回答
