### ISSUE TITLE
怎样查看所选择的算法，以及算法的具体模型参数？

### ISSUE THREAD

**Issue by hello-the-vsworld** [DataCanvasIO/HyperTS#104]
当model = experiment.run()后，会给予我一个相对最好的算法，我怎么知道这个算法的具体名称和其训练的模型参数，例如其权重、偏置是什么样的呢？我又来提问题来了

**Comment by zhangxjohn** [comment]
![image](https://github.com/DataCanvasIO/HyperTS/assets/80235074/6dd91102-e2ff-402f-a62a-7fe210d91abf)
可以从model里取estimater.
