### ISSUE TITLE
最终预测结果图片样式

### ISSUE THREAD

**Issue by hello-the-vsworld** [DataCanvasIO/HyperTS#106]
您好，
  预测结果的图片样式可以修改吗？比如把中间的网格线去除，或者引入python扩展包进行结果预测，显示出可以用于论文撰写要求的图片，下面添加的图片附件是我想达到的效果，感谢！
![111](https://github.com/DataCanvasIO/HyperTS/assets/87103020/089f6feb-71a0-4ac4-a268-c42323195237)
![图片样式](https://github.com/DataCanvasIO/HyperTS/assets/87103020/36455de8-88d0-4749-a793-c5ad15b15532)

**Comment by zhangxjohn** [comment]
您好，不好意思，这个需求无法满足。
如果您个人有定制化的需求，您可以按照您的需求自己绘图，或者修改(https://github.com/DataCanvasIO/HyperTS/tree/main/hyperts/utils/plot.py)
中的内容。

**Comment by hello-the-vsworld** [comment]
您好，可以使用matplotlib等第三方库进行结果预测的绘图吗？如果可以，怎么较预测结果绘制在其中？







直到太阳升起
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DataCanvasIO/HyperTS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月28日(星期一) 上午10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DataCanvasIO/HyperTS] 最终预测结果图片样式 (Issue #106)





 
您好，不好意思，这个需求无法满足。
 如果您个人有定制化的需求，您可以按照您的需求自己绘图，或者修改(https://github.com/DataCanvasIO/HyperTS/tree/main/hyperts/utils/plot.py)
 中的内容。

**Comment by zhangxjohn** [comment]
可以使用matplotlib绘制。
您可以参考(https://github.com/DataCanvasIO/HyperTS/tree/main/hyperts/utils/plot.py)中使用的变量进行绘制。
所有的变量（e.g., X_train, y_train, X_text, y_text, y_pred）您在运行过程中均可以获得，根据自己的需求直接绘制即可。
