### ISSUE TITLE
预测时不预测负值，只预测正值

### ISSUE THREAD

**Issue by hello-the-vsworld** [DataCanvasIO/HyperTS#107]
![错误](https://github.com/DataCanvasIO/HyperTS/assets/87103020/3b2cb638-fac3-485d-a3a3-ed2e78c7a7a4)
从图中可知，很明显不对负值进行预测，是否是版本问题，拉取最新版可解决此问题吗？

**Comment by zhangxjohn** [comment]
可以

**Comment by hello-the-vsworld** [comment]
好的
&nbsp;


直到太阳升起
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaojing ***@***.***&gt;; 
发送时间: 2023年9月2日(星期六) 上午8:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DataCanvasIO/HyperTS] 预测时不预测负值，只预测正值 (Issue #107)





 
可以

**Comment by hello-the-vsworld** [comment]
拉取测试版需要将以前下载的正式版本卸载吗？




直到太阳升起
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DataCanvasIO/HyperTS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月2日(星期六) 上午8:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DataCanvasIO/HyperTS] 预测时不预测负值，只预测正值 (Issue #107)





 
可以

**Comment by hello-the-vsworld** [comment]
我尝试了从github 下载最新的代码，然后离线安装，通过pip list 查询到了库的版本，我不清楚是否是最新版，请求给我点提示，到底怎么拉取最新的开发版hyperts，这对我很重要，我需要用其完成我论文的最后一部分。
![库版本](https://github.com/DataCanvasIO/HyperTS/assets/87103020/06f36baf-2d5d-4525-b8ee-e261075adf35)
![下载的压缩包](https://github.com/DataCanvasIO/HyperTS/assets/87103020/4f39614a-c6dd-4459-bd31-b7643f2de2d0)
![预测](https://github.com/DataCanvasIO/HyperTS/assets/87103020/79239314-1352-4611-9566-3a2ad84e240b)

**Comment by zhangxjohn** [comment]
感谢您支持与使用HyperTS，由于精力有限，我们不提供您日常的科研中遇到的问题。对于安装以及其他非本项目的issues，您可以百度，google，或者咨询您的老师，同学和朋友，谢谢！
如若您在论文中使用了本项目，请引用本项目，引用方式可参考README。
