### ISSUE TITLE
Some Issues on Time Series Prediction Results

### ISSUE THREAD

**Issue by Layonhuuu** [DataCanvasIO/HyperTS#110]
Why is my prediction only positive?And I think if the predicted results have been scaled, how can we restore the predicted results to before being scaled?I hope someone can help me. QAQ

![perdict_result](https://github.com/DataCanvasIO/HyperTS/assets/119099762/d75277a2-09f4-48f9-b317-c6b249991317)
![test_target data](https://github.com/DataCanvasIO/HyperTS/assets/119099762/2bed97fd-5c82-4f56-9c71-acf5914333cc)

**Comment by zhangxjohn** [comment]
This issue has been resolved. You can now pull the latest code into your site-packages.

**Comment by Layonhuuu** [comment]
thanks！Can I just reinstall it directly？pip install hyperts？

**Comment by zhangxjohn** [comment]
This issue has been resolved. However, the latest version has not been released yet, so you cannot install it at the moment. You only pull the dev code.

**Comment by Layonhuuu** [comment]
你好，再次打扰一下，
我能问下修改的这个bug具体在开发代码( dev code)哪个模块里面吗？是在hyperts\utils\transformers.py里面吗？

**Comment by zhangxjohn** [comment]
`hyperts/framework/wrappers/dl_wrappers.py` and `hyperts/framework/wrappers/stats_wrappers.py`

**Comment by Layonhuuu** [comment]
Thanks！

**Comment by Layonhuuu** [comment]
抱歉再次打扰到你，我按照你说的将GitHub上的代码下载下来（zip文件包），然后将zip压缩文件中Hyperts文件夹中的文件替换为我环境site-packages里的对应文件 仍然出现同样的问题，预测结果只有正值没有负值，且峰值对应不上的问题，请问该如何解决呢？

**Comment by zhangxjohn** [comment]
我猜测你打开的方式不对：(
可以看看version是0.2.0， 还是 0.2.1.  如果是0.2.0说明你的环境没有适配。建议用一下方式替换：
```
git clone git@github.com:DataCanvasIO/HyperTS.git
cd HyperTS
pip install -e . 
pip install tensorflow #optional
```

**Comment by Layonhuuu** [comment]
十分感谢！问题解决了

**Comment by Layonhuuu** [comment]
抱歉再次打扰你，我有个问题是，我在我自己的自定义搜索空间(custom_search_space)里，只保留了其中一个模型（例如enable_lstnet = True，其他三个模型均为false，只定义对应的模型的参数搜索空间）然而在实验进行时，控制台给出的信息显示，仍调用了其他模型（例如enable_hybirdrnn），我想请教一下这个问题是如何产生的？以及如何避免呢？调用参数如下
custom_search_space = DLForecastSearchSpace(enable_deepar = False, enable_hybirdrnn = False,  enable_lstnet = True, enable_nbeats=False,  lstnet_init_kwargs={ 'optimizer': 'adam',  'loss': Choice(['mae', 'mse', 'huber_loss']), 'rnn_type': Choice(['gru', 'lstm']), 'skip_rnn_type': Choice(['gru', 'lstm']),  'cnn_filters': Choice([64]*2+[128]*3+[256]*2)})

experiment = make_experiment(train_data=train_data.copy(), task='forecast',  eval_data=eval_data, mode='dl', timestamp='时间(s)',  max_trials=5, covariables=['xxx', ‘aaa’ ], reward_metric='rmse', optimize_direction='min', ensemble_size=None, search_space=custom_search_space, searcher=MCTSSearcher(custom_search_space, use_meta_learner=True, max_node_space=1000,candidates_size=10, optimize_direction='min'),  log_level='INFO', random_state=0)

model = experiment.run(epochs=2, final_train_epochs=5,batch_size=1024,）

**Comment by zhangxjohn** [comment]
你把` searcher=MCTSSearcher(custom_search_space, use_meta_learner=True, max_node_space=1000,candidates_size=10, optimize_direction='min')`删除看看。

**Comment by Layonhuuu** [comment]
还是会应用hybirdrnn模型，但是定义了enable_hybirdrnn = False.

**Comment by zhangxjohn** [comment]
按道理应该是不会走hybirdrnn了。如果可以的话，你可以Debug一下，看看问题出现在哪，我目前想象不到问题位置。

**Comment by zhangxjohn** [comment]
断点位置：[HyperTS](https://github.com/DataCanvasIO/HyperTS/tree/main)/[hyperts](https://github.com/DataCanvasIO/HyperTS/tree/main/hyperts)/[framework](https://github.com/DataCanvasIO/HyperTS/tree/main/hyperts/framework)/[search_space](https://github.com/DataCanvasIO/HyperTS/tree/main/hyperts/framework/search_space)
/macro_search_space.py
754行和851行。

**Comment by Layonhuuu** [comment]
你好，抱歉再次打扰，在构建实验时，我尝试自定义损失函数，模式为“dl”，运行时给出如下信息
11-15 14:12:41 W hyperts.f.d._base.py 689 - In dl model, ['custom_metric'] is not supported, so ['rmse'] will be called. 
所以在深度学习里不能自定义损失函数（loss）吗？

**Comment by zhangxjohn** [comment]
是的。

**Comment by Layonhuuu** [comment]
你好，再次叨扰^.^，在结果绘制中，采用提供的接口
model.plot(forecast=forecast, actual=test_data, var_id='xxx', interactive=False,show_forecast_interval=False)
我只传输了forecast与actual，为和图片中还有一条数据是historical？请问一下这个historical的结果在哪里能看呢？我采用
forecast = model.predict(X_test) 输出的结果也只有时间戳与预测列，并没有Historical。所以就想请教一下QAQ。此外还有个小问题是，之前模型调用窗口的问题解决之后，我只调用了DeepAR模型 这模型应该会返回两列数据，均值与方差？在预测结果中也只有一列，没有方差，请问哪里能找到呢？
![Figure 2023-11-15 165820](https://github.com/DataCanvasIO/HyperTS/assets/119099762/f35ced38-677d-4e92-96e3-4375874cb49b)

**Comment by Layonhuuu** [comment]
"historical会显示训练集的一小段数据",对这句话有点小疑问呢？因为如果是训练集的数据的话，以前的代码试验结果绘制的图像里含有的Historical数据峰值都很小，在1.5-3.5之间，而给模型训练的数据集的峰值分布不可能这么小QAQ，请问可以在hyperts框架的哪里看到关于这个Historica数据的调用哇？

**Comment by Layonhuuu** [comment]
“为了统一所有模型的输出，DeepAR只输出了均值”，那就有个小问题就是，在示例结果展示里，图片有upperbound与lowerbound，这俩值是怎么算出来的呢？
![Actual_vs_Forecast](https://github.com/DataCanvasIO/HyperTS/assets/119099762/db85d636-ca19-4051-b862-b6d1292c7e84)

**Comment by zhangxjohn** [comment]
那就说来话长了。

**Comment by zhangxjohn** [comment]
plot的调用可以查看一下文档里的API。

**Comment by Layonhuuu** [comment]
> 那就说来话长了。

请问能方便透露下吗？QAQ

**Comment by zhangxjohn** [comment]
通过贝叶斯推断的。

**Comment by Layonhuuu** [comment]
感谢！
