### ISSUE TITLE
关于make_experiment参数的问题

### ISSUE THREAD

**Issue by shuangshui** [DataCanvasIO/HyperTS#111]
forecast_train_data_periods 这个参数是用来对train_data截取用来做train_data的吗
dl_forecast_window和dl_forecast_horizon什么区别，单位是个数还是小时？

假如我训练设定过去365天预测未来的multi-step 30天？
predict()函数是滚动的吗

**Comment by zhangxjohn** [comment]
Q1：```forecast_train_data_periods 这个参数是用来对train_data截取用来做train_data的吗```
A1：是的。

Q2：```dl_forecast_window和dl_forecast_horizon什么区别，单位是个数还是小时？```
A1： ```dl_forecast_window```是样本的窗口大小，```dl_forecast_horizon```是样本间滑窗间隔，单位是数据集的```freq```。

Q3：```假如我训练设定过去365天预测未来的multi-step 30天？predict()函数是滚动的吗```
A3：是滚动的。

**Comment by shuangshui** [comment]
> Q1：`forecast_train_data_periods 这个参数是用来对train_data截取用来做train_data的吗` A1：是的。
> 
> Q2：`dl_forecast_window和dl_forecast_horizon什么区别，单位是个数还是小时？` A2： `dl_forecast_window`是样本的窗口大小，`dl_forecast_horizon`是样本间滑窗间隔，单位是数据集的`freq`。
> 
> Q3：`假如我训练设定过去365天预测未来的multi-step 30天？predict()函数是滚动的吗` A3：是滚动的。

关于第二个问题，是不是意味着：我用过去365天的数据来预测未来30天？dl_forecast_window=365，dl_forecast_horizon=30？
这是一个多步多变量同时预测的seq2seq问题？

关于第三个问题，假设我用1到365 的真实值预测了 366到396三十个点，下一步是不是用2到366 真实值（其中366不是上一步预测，而是拿了真实值）预测了 367到397三十个点？

多谢大神答复

**Comment by zhangxjohn** [comment]
Q1:   ```关于第二个问题，是不是意味着：我用过去365天的数据来预测未来30天？dl_forecast_window=365，dl_forecast_horizon=30？
这是一个多步多变量同时预测的seq2seq问题？````

A1:   不是，可以知乎找一找神经网络时间序列预测的一个教程看看数据预处理的过程，就会明白了。

Q2:   ```关于第三个问题，假设我用1到365 的真实值预测了 366到396三十个点，下一步是不是用2到366 真实值（其中366不是上一步预测，而是拿了真实值）预测了 367到397三十个点？```

A2:  这个可以找一下多步预测的过程处理的教程。简单描述一下：x1,x2,x3->x4,x5   x3,x4,x5 ->x6,x7

**Comment by shuangshui** [comment]
> x3

x1,x2,x3->x4,x5； x3,**x4,x5** ->x6,x7
这个x4 x5是真实值，还是上一步预测得到的？

**Comment by zhangxjohn** [comment]
预测得到的，滚动预测。后期的是`预测值`预测`预测值`。
