### ISSUE TITLE
請問範例中用mode:'stats' 且task = multivariate-forecast時, predict 是如何預測的?

### ISSUE THREAD

**Issue by 02hao09** [DataCanvasIO/HyperTS#112]
我想了解用mode:'stats' 且task = multivariate-forecast時, model.predict() 帶入的值是否會影響預測值?
我嘗試使用亂數, 結果都是一樣的, 想請教model是如何預測的 謝謝

**Comment by zhangxjohn** [comment]
你好，stats&multivariate-forecast采用了VAR模型，可以参考VAR模型的算法原理。

**Comment by 02hao09** [comment]
> 你好，stats&multivariate-forecast采用了VAR模型，可以参考VAR模型的算法原理。

根據文檔有看到     
 Task could be 'univariate-forecast', 'multivariate-forecast', and 'univariate-binaryclass',
        'univariate-multiclass', 'multivariate-binaryclass, and ’multivariate-multiclass’.
        Notably, task can also configure 'forecast', 'classification', 'regression'，and 'detection'.
        Besides, 'tsf', 'utsf'，'mtsf', 'tsc', 'tsr', 'tsd'('tsa', 'tsad') are also ok.

想再請教一個問題, 那選擇forecast是單變量預測模型還是多變量預測模型呢?

**Comment by 02hao09** [comment]
謝謝!
