### ISSUE TITLE
AttributeError: module 'pandas' has no attribute 'Int64Index'

### ISSUE THREAD

**Issue by Billy1900** [DataCanvasIO/HyperTS#113]
I have met an error when I want to do like this
```python
data = pd.read_feather("data_w50_s10.feather")
# split data
train_data, test_data = train_test_split(data, test_size=0.2, shuffle=False)
model = make_experiment(train_data,
                        task='classification',
                        mode='dl',
                        tf_gpu_usage_strategy=1,
                        reward_metric='accuracy',
                        max_trials=30,
                        early_stopping_rounds=10).run()
```

AttributeError: module 'pandas' has no attribute 'Int64Index'

**Comment by zhangxjohn** [comment]
Where is the error position when you ran your script? 

I guess this is the problem of `pandas`. you can alternate version of `pandas`.

**Comment by Billy1900** [comment]
> Where is the error position when you ran your script?
> 
> I guess this is the problem of `pandas`. you can alternate version of `pandas`.

this line: model = make_experiment(train_data,

Yeah, but when I change to pandas 1.4.0 a lower version (previously I use 2.2.0), the problem is still there.

**Comment by zhangxjohn** [comment]
Sorry, our environments can't replicate your problem unless you provide more information.
Perhaps, you can also create a new environment to find the root cause of the problem.
