### ISSUE TITLE
In models with integration (`d > 0`) or seasonal integration (`D > 0`), trend terms of lower order than `d + D` cannot be

### ISSUE THREAD

**Issue by Shanshan122** [DataCanvasIO/HyperTS#35]
Task type: forecast
Covariate columns: 9 columns
Prediction column: 1 column

I am getting the following error when using HyperTS:
search:   0%|          | 0/3 [00:00<?, ?it/s]04-06 15:27:10 E hypernets.m.hyper_model.py 71 - run_trail failed! trail_no=1
04-06 15:27:10 E hypernets.m.hyper_model.py 73 - Traceback (most recent call last):
  File "/root/miniconda3/envs/hyperTS/lib/python3.8/site-packages/hypernets/model/hyper_model.py", line 66, in _run_trial
    estimator.fit(X, y, **fit_kwargs)
  File "/root/miniconda3/envs/hyperTS/lib/python3.8/site-packages/hyperts/hyper_ts.py", line 118, in fit
    self.model.fit(X_transformed, y, **kwargs)
  File "/root/miniconda3/envs/hyperTS/lib/python3.8/site-packages/hyperts/framework/wrappers/stats_wrappers.py", line 80, in fit
    model = ARIMA(endog=y, order=(p, d, q), trend=trend,
  File "/root/miniconda3/envs/hyperTS/lib/python3.8/site-packages/statsmodels/tsa/arima/model.py", line 146, in __init__
    raise ValueError(
ValueError: In models with integration (`d > 0`) or seasonal integration (`D > 0`), trend terms of lower order than `d + D` cannot be (as they would be eliminated due to the differencing operation). For example, a constant cannot be included in an ARIMA(1, 1, 1) model, but including a linear trend, which would have the same effect as fitting a constant to the differenced data, is allowed.

search:  33%|███▎      | 1/3 [00:00<00:00,  3.02it/s]INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
search:  67%|██████▋   | 2/3 [00:02<00:01,  1.38s/it]INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.

**Comment by zhangxjohn** [comment]
This is a conflict in the ARIMA parameter space, but it should not affect the final searched model.  You can post more detailed code information to help me reproduce the error process.
