### ISSUE TITLE
why not ensemble learning(like xgboost) in ts forecast?

### ISSUE THREAD

**Issue by huyaoyao0904** [DataCanvasIO/HyperTS#44]

**Comment by zhangxjohn** [comment]
HyperTS has implemented some of the best proven time series models(e.g., ARIMA, Prophet, GRU) in the current version, but supports custom models to be placed into the search space.  If you want to add an XGBoost model, refer to [custom_search_space](https://github.com/DataCanvasIO/HyperTS/blob/main/examples/08_custom_search_space_02.ipynb).

**Comment by huyaoyao0904** [comment]
> HyperTS has implemented some of the best proven time series models(e.g., ARIMA, Prophet, GRU) in the current version, but supports custom models to be placed into the search space. If you want to add an XGBoost model, refer to [custom_search_space](https://github.com/DataCanvasIO/HyperTS/blob/main/examples/08_custom_search_space_02.ipynb).

OK，thanks.
