### ISSUE TITLE
test_size error

### ISSUE THREAD

**Issue by weizhang-Indi** [DataCanvasIO/HyperTS#49]
Hi! I have an error in training a TS forecast model, it says:
ValueError: test_size=270 should be either positive and smaller than the number of samples 270 or a float in the (0, 1) range.
This is my data shape：
![Screenshot from 2022-08-01 17-35-13](https://user-images.githubusercontent.com/35283546/182119639-3f02fd6b-8251-4621-b997-5c038307be4b.png)
Can you help me solve this problem?  Thank you！

**Comment by zhangxjohn** [comment]
What are your initialization parameters for `make_experiment`?
What is the wrong position?

**Comment by weizhang-Indi** [comment]
initialization:
![Screenshot from 2022-08-01 19-26-21](https://user-images.githubusercontent.com/35283546/182138310-3ab32fcc-bd5b-4e14-97e9-3628f6e6d62c.png)
wrong position:
![Screenshot from 2022-08-01 19-26-36](https://user-images.githubusercontent.com/35283546/182138381-0c495ec0-7103-450c-8d11-48270856664f.png)

**Comment by zhangxjohn** [comment]
Hello，thanks.  Please run the follow code to check the size of the data **period**. If it is 270, you can fix the problem by setting `eval_size`(in `make_experinet`) to an integer less than 270.

-----------------------------------------------------------------------------------------------------------------------------------------------
`import pandas as pd`
`from hyperts.utils import get_tool_box`

`df = pd.DataFrame('./your_dataset.csv')`

`tb = get_tool_box(df)`

`period = tb.fft_infer_period(df.iloc[:, 1])  # your target column`
`print(period)`

**Comment by weizhang-Indi** [comment]
> Hello，thanks. Please run the follow code to check the size of the data **period**. If it is 270, you can fix the problem by setting `eval_size`(in `make_experinet`) to an integer less than 270.
> 
> `import pandas as pd` `from hyperts.utils import get_tool_box`
> 
> `df = pd.DataFrame('./your_dataset.csv')`
> 
> `tb = get_tool_box(df)`
> 
> `period = tb.fft_infer_period(df.iloc[:, 1]) # your target column` `print(period)`

Thank you! The data period show like this, it is **2**:
![image](https://user-images.githubusercontent.com/35283546/182277326-8d98eb6b-6409-4dca-8c83-eb3bd826b0d9.png)

**Comment by weizhang-Indi** [comment]
> Hello，thanks. Please run the follow code to check the size of the data **period**. If it is 270, you can fix the problem by setting `eval_size`(in `make_experinet`) to an integer less than 270.
> 
> `import pandas as pd` `from hyperts.utils import get_tool_box`
> 
> `df = pd.DataFrame('./your_dataset.csv')`
> 
> `tb = get_tool_box(df)`
> 
> `period = tb.fft_infer_period(df.iloc[:, 1]) # your target column` `print(period)`

Thank you! It works now!
