### ISSUE TITLE
data_cleaner_args 参数问题

### ISSUE THREAD

**Issue by Shanshan122** [DataCanvasIO/HyperTS#65]
数据清洗参数在make_experiment(）设置无效，experiment.py文件中未传入该参数。

例如：experiment = make_experiment(train_data=train_data.copy(),
                             task='forecast',
                             timestamp='TimeStamp',
                             covariates=['HourSin', 'WeekCos', 'CBWD'],
                        data_cleaner_args = {
                                     'correct_object_dtype': False,
                                     'int_convert_to': 'str',
                                      'drop_constant_columns': True,
                                      'drop_duplicated_columns': True,
                                      'drop_idness_columns': True,
                         },
                             max_trials=1)

**Comment by Shanshan122** [comment]
experiment.py文件中：
  # 7. Covarite Transformer
    if covariates is not None:
        from hyperts.utils.transformers import CovariateTransformer
        cs = CovariateTransformer(covariables=covariates).fit(X_train)
        actual_covariates = cs.covariables_
    else:
        from hyperts.utils.transformers import IdentityTransformer
        cs = IdentityTransformer().fit(X_train)
        actual_covariates = covariates

**Comment by zhangxjohn** [comment]
现在可以修改 ``data_cleaner_args`` 了。
