### ISSUE TITLE
关于 HybirdRNN 解决多变量时序分类的问题

### ISSUE THREAD

**Issue by Shanshan122** [DataCanvasIO/HyperTS#67]
在自定义搜索空间时，代码报错。自定义如下：

`df = load_basic_motions()
train_df, test_df = train_test_split(df, test_size=0.2)
from hyperts.framework.search_space.macro_search_space import DLClassRegressSearchSpace
custom_search_space = DLClassRegressSearchSpace(enable_hybirdrnn=True,
                 enable_lstnet=False,
                 enable_inceptiontime=False,         
                                        hybirdrnn_init_kwargs={
                                                'task': 'classification' }
                                            )

experiment = make_experiment(train_data=train_df.copy(), 
                             task='classification',
                             mode='dl',
                                search_space=custom_search_space,
                             target='target')`

报错如下：
11-01 16:03:29 E hypernets.m.hyper_model.py 83 - run_trail failed! trail_no=2
11-01 16:03:29 E hypernets.m.hyper_model.py 85 - Traceback (most recent call last):
  File "E:\Anaconda\install\lib\site-packages\hypernets\model\hyper_model.py", line 78, in _run_trial
    estimator.fit(X, y, **fit_kwargs)
  File "E:\Anaconda\install\lib\site-packages\hyperts\hyper_ts.py", line 262, in fit
    self.model.fit(X_transformed, y, **kwargs)
  File "E:\Anaconda\install\lib\site-packages\hyperts\framework\wrappers\dl_wrappers.py", line 71, in fit
    self.model.fit(X, y, **fit_kwargs)
  File "E:\Anaconda\install\lib\site-packages\hyperts\framework\dl\_base.py", line 384, in fit
    X, y = self._preprocessor(X, y)
  File "E:\Anaconda\install\lib\site-packages\hyperts\framework\dl\_base.py", line 827, in _preprocessor
    self.meta = MetaTSCprocessor(task=self.task)
TypeError: __init__() got an unexpected keyword argument 'task'

**Comment by zhangxjohn** [comment]
hybirdrnn_init_kwargs={'task': 'classification' }
不用传`task`参数。

**Comment by Shanshan122** [comment]
> hybirdrnn_init_kwargs={'task': 'classification' } 不用传`task`参数。

试了一下，还是报错：
custom_search_space = DLClassRegressSearchSpace(enable_hybirdrnn=True,
                 enable_lstnet=False,
                 enable_inceptiontime=False,         
                                        hybirdrnn_init_kwargs={
                                               'learning_rate':0.01,
                                                 'reducelr_patience': 5,
                                                'earlystop_patience': 15,
                                        }
                                            )

experiment = make_experiment(train_data=train_df.copy(), 
                             task='classification',
                             mode='dl',
                                search_space=custom_search_space,
                             target='target')

**Comment by Shanshan122** [comment]
已解决。（更新了包）
