### ISSUE TITLE
ImportError: DLL load failed while importing _parquet: 内存资源不足，无法处理此命令

### ISSUE THREAD

**Issue by mokeeqian** [DataCanvasIO/HyperTS#72]
```
ImportError                               Traceback (most recent call last)
Cell In [2], line 1
----> 1 from hyperts import make_experiment
      2 from hyperts.datasets import load_network_traffic
      4 from sklearn.model_selection import train_test_split

File d:\Software\Anaconda\envs\hyperts\lib\site-packages\hyperts\__init__.py:13
      9         logging.set_level('warn')
     11 _init()
---> 13 from .experiment import make_experiment
     14 from .framework.compete import TSCompeteExperiment
     15 from .hyper_ts import HyperTS, HyperModel, HyperTSEstimator

File d:\Software\Anaconda\envs\hyperts\lib\site-packages\hyperts\experiment.py:7
      5 from hypernets.searchers import make_searcher
      6 from hypernets.discriminators import make_discriminator
----> 7 from hypernets.experiment.cfg import ExperimentCfg as cfg
      8 from hypernets.tabular.cache import clear as _clear_cache
      9 from hypernets.utils import logging, isnotebook, load_module

File d:\Software\Anaconda\envs\hyperts\lib\site-packages\hypernets\experiment\__init__.py:7
      2 __author__ = 'yangjian'
      3 """
      4 
...
     42                               FileDecryptionProperties)
     43 from pyarrow.fs import (LocalFileSystem, FileSystem,
     44                         _resolve_filesystem_and_path, _ensure_filesystem)

ImportError: DLL load failed while importing _parquet: 内存资源不足，无法处理此命令。
```

**Comment by zhangxjohn** [comment]
> ```
> ImportError                               Traceback (most recent call last)
> Cell In [2], line 1
> ----> 1 from hyperts import make_experiment
>       2 from hyperts.datasets import load_network_traffic
>       4 from sklearn.model_selection import train_test_split
> 
> File d:\Software\Anaconda\envs\hyperts\lib\site-packages\hyperts\__init__.py:13
>       9         logging.set_level('warn')
>      11 _init()
> ---> 13 from .experiment import make_experiment
>      14 from .framework.compete import TSCompeteExperiment
>      15 from .hyper_ts import HyperTS, HyperModel, HyperTSEstimator
> 
> File d:\Software\Anaconda\envs\hyperts\lib\site-packages\hyperts\experiment.py:7
>       5 from hypernets.searchers import make_searcher
>       6 from hypernets.discriminators import make_discriminator
> ----> 7 from hypernets.experiment.cfg import ExperimentCfg as cfg
>       8 from hypernets.tabular.cache import clear as _clear_cache
>       9 from hypernets.utils import logging, isnotebook, load_module
> 
> File d:\Software\Anaconda\envs\hyperts\lib\site-packages\hypernets\experiment\__init__.py:7
>       2 __author__ = 'yangjian'
>       3 """
>       4 
> ...
>      42                               FileDecryptionProperties)
>      43 from pyarrow.fs import (LocalFileSystem, FileSystem,
>      44                         _resolve_filesystem_and_path, _ensure_filesystem)
> 
> ImportError: DLL load failed while importing _parquet: 内存资源不足，无法处理此命令。
> ```

您好，请提供一下可以复现出现该问题的源码与数据，便于我们定位。

**Comment by zhangxjohn** [comment]
目前判断您安装其他packages，可能hyperts的环境被破坏了，建议重新安装hyperts查看是否会出现上述问题。

**Comment by mokeeqian** [comment]
> 

源码与数据即是官网docs里的快速开始的sample code，采用如下命令安装的：
```
conda install -c conda-forge hyperts
```

现在使用如下命令重新安装了hyperts，问题得到解决。
```
conda install -c conda-forge prophet==1.0.1
pip install hyperts tensorflow
```
感谢！
