### ISSUE TITLE
Support numpy >= 1.22

### ISSUE THREAD

**Issue by DManowitz** [DataCanvasIO/HyperTS#77]
Numpy is several versions beyond 1.21.x now.  Requesting support for numpy >= 1.22.

**Comment by zhangxjohn** [comment]
A higher version of numpy would conflict with the version of some libraries (e.g., tf), so we restricted it to be safe. Thank you for your support, we will solve these problems in the future.

> Numpy is several versions beyond 1.21.x now. Requesting support for numpy >= 1.22.
