### ISSUE TITLE
单变量时序预测报错问题

### ISSUE THREAD

**Issue by wuzhitao** [DataCanvasIO/HyperTS#78]
使用的是平台提供的固定单变量预测数据集，测试代码如下：
from hyperts import make_experiment
from hyperts.datasets import load_fixed_univariate_forecast_dataset
from sklearn.model_selection import train_test_split

df = load_fixed_univariate_forecast_dataset()

train_data, test_data = train_test_split(df, test_size=30, shuffle=False)

experiment = make_experiment(train_data=train_data.copy(),
                             task='univariate-forecast',
                             timestamp='ds',
                             max_trials=5,
                             log_level=2
                             )
model = experiment.run()
直接运行会提示：Error in atexit._run_exitfuncs
调试跟踪发现在：...hyperts\lib\logging\__init__.py (L1089) 报异常 self.handleError(record)
请问可能是什么原因？谢谢
运行环境：Win11/Python 3.8.0/hypernets(0.2.5.7)/hyperts(0.2.0)/prophet(1.1.1)/numpy(1.21.6)/pandas(1.5.2)/scikit-learn(1.2.0)/scipy(1.10.0)/sktime(0.15.1)/statsmodels(0.13.5)

**Comment by zhangxjohn** [comment]
HyperTS中并没有`hyperts\lib\logging_init.py `文件，目前怀疑您的环境存在冲突及不可预知的混乱，您可以创建一个干净的新环境，然后重新安装hyperts看是否还有上述问题。

**Comment by wuzhitao** [comment]
您好，
十分感谢您的回复！
我用nminiconda重新搭建了一个干净的环境
1）conda create -n hyperts python==3.8
2）conda activate hyperts
3）pip install hyperts
整个环境安装过程正常无报错
然后我重新执行了一下测试代码，依然会在结束的地方出现 Error in atexit._run_exitfuncs
log完整如下：
01-16 17:28:51 E hyperts.u.plot.py 19 - Importing plotly failed. Interactive plots will not work.
01-16 17:28:51 I hyperts.experiment.py 387 - If the data contains covariates, specify the covariate column names.
01-16 17:28:51 I hyperts.experiment.py 590 - Inference task type could be [univariate-forecast].
01-16 17:28:51 I hyperts.experiment.py 602 - No reward metric specified, use "mae" for univariate-forecast task by default.
01-16 17:28:51 I hyperts.experiment.py 604 - Reward_metric is [mae].
01-16 17:28:51 I hyperts.experiment.py 621 - Optimize direction is [min].
Importing plotly failed. Interactive plots will not work.
01-16 17:28:52 I hyperts.experiment.py 639 - Searcher is [EvolutionSearcher].
01-16 17:28:52 I hypernets.e.compete.py 1500 - create experiment with ['data_preprocessing', 'space_searching', 'final_ensemble'], random_state=7771   
01-16 17:28:52 I hyperts.experiment.py 691 - make_experiment with train data:(2875, 1), test data:None, eval data:None, target:['y'], task:univariate-forecast
01-16 17:28:52 I hypernets.e.compete.py 1521 - ToolBox data memory usage: 0.000, free=6.053
01-16 17:28:52 I hypernets.e.compete.py 1536 - fit_transform data_preprocessing with columns: ['ds']
01-16 17:28:52 I hypernets.e.compete.py 1521 - ToolBox data memory usage: 0.000, free=6.049
01-16 17:28:52 I hypernets.e.compete.py 1536 - fit_transform space_searching with columns: ['ds']
01-16 17:28:52 I hypernets.c.meta_learner.py 22 - Initialize Meta Learner: dataset_id:a9cb8e6397383bef0e65a618fff0d464
01-16 17:28:52 I hypernets.c.callbacks.py 235 - 
Trial No:1
--------------------------------------------------------------
(0) estimator_options.hp_or:                                0
(1) Module_ProphetForecastEstimator_3.outlier:           clip
(2) Module_ProphetForecastEstimator_3.changepoint_range: 0.95
(3) Module_ProphetForecastEstimator_3.seasonality_mode:additive
(4) Module_ProphetForecastEstimator_3.seasonality_prior_scale:1.0
(5) Module_ProphetForecastEstimator_3.holidays_prior_scale:0.1
(6) Module_ProphetForecastEstimator_3.changepoint_prior_scale:0.1
--------------------------------------------------------------
trial 1 begin
01-16 17:28:52 D hypernets.c.search_space.py 124 - Compile Space: compiled 6 modules in 0.0 seconds.
01-16 17:28:52 D hypernets.c.search_space.py 147 - Forward Space: forwarded 6 modules in 0.0 seconds.
01-16 17:28:52 I hyperts.hyper_ts.py 251 - estimator is transforming the train set
01-16 17:28:52 D hypernets.t.dataframe_mapper.py 299 - fit_transform 1 columns with:
Pipeline(steps=[('Module_TimeSeriesHyperTransformer_1',
                 <hyperts.utils.transformers.TimeSeriesTransformer object at 0x0000029015F49850>)])
01-16 17:28:52 D hypernets.t.dataframe_mapper.py 311 - fit_transform Pipeline, X shape:(2568, 1), steps:['Module_TimeSeriesHyperTransformer_1']        
01-16 17:28:52 D hypernets.t.dataframe_mapper.py 320 - columns:1
01-16 17:28:52 D hypernets.t.dataframe_mapper.py 323 - transformed_names_:1
01-16 17:28:54 I hyperts.hyper_ts.py 268 - taken 0.28965234756469727s
01-16 17:28:54 I hyperts.hyper_ts.py 275 - estimator is predicting the data
01-16 17:28:54 D hypernets.t.dataframe_mapper.py 299 - fit_transform 1 columns with:
Pipeline(steps=[('Module_TimeSeriesHyperTransformer_1',
                 <hyperts.utils.transformers.TimeSeriesTransformer object at 0x0000029017633820>)])
01-16 17:28:54 D hypernets.t.dataframe_mapper.py 311 - fit_transform Pipeline, X shape:(366, 1), steps:['Module_TimeSeriesHyperTransformer_1']
01-16 17:28:54 D hypernets.t.dataframe_mapper.py 320 - columns:1
01-16 17:28:54 D hypernets.t.dataframe_mapper.py 323 - transformed_names_:1
01-16 17:28:54 I hyperts.hyper_ts.py 303 - taken 0.19500398635864258s
01-16 17:28:54 I hypernets.c.callbacks.py 239 - trial end. reward:0.3908477732330015, improved:False, elapsed:0.5287027359008789
01-16 17:28:54 I hypernets.c.callbacks.py 240 - Total elapsed:1.9171452522277832
01-16 17:28:54 I hypernets.d.in_process_dispatcher.py 110 - Trial 2 done, reward: 0.3908477732330015, best_trial_no:1, best_reward:0.3034834381243608  

01-16 17:28:54 I hypernets.c.callbacks.py 235 - 
Trial No:3
--------------------------------------------------------------
(0) estimator_options.hp_or:                                0
(1) Module_ProphetForecastEstimator_3.outlier:   none-outlier
(2) Module_ProphetForecastEstimator_3.changepoint_range: 0.95
01-16 17:28:54 D hypernets.c.search_space.py 124 - Compile Space: compiled 6 modules in 0.0 seconds.
01-16 17:28:54 D hypernets.c.search_space.py 147 - Forward Space: forwarded 6 modules in 0.0 seconds.
01-16 17:28:54 I hyperts.hyper_ts.py 251 - estimator is transforming the train set
01-16 17:28:54 D hypernets.t.dataframe_mapper.py 299 - fit_transform 1 columns with:
Pipeline(steps=[('Module_TimeSeriesHyperTransformer_1',
                 <hyperts.utils.transformers.TimeSeriesTransformer object at 0x0000029017646EE0>)])
01-16 17:28:54 D hypernets.t.dataframe_mapper.py 311 - fit_transform Pipeline, X shape:(2568, 1), steps:['Module_TimeSeriesHyperTransformer_1']
01-16 17:28:54 D hypernets.t.dataframe_mapper.py 320 - columns:1
01-16 17:28:54 D hypernets.t.dataframe_mapper.py 323 - transformed_names_:1
17:28:54 - cmdstanpy - INFO - Chain [1] start processing
17:28:55 - cmdstanpy - INFO - Chain [1] done processing
Error in atexit._run_exitfuncs:



 
发件人： Xiaojing Zhang
发送时间： 2023-01-16 16:45
收件人： DataCanvasIO/HyperTS
抄送： wuzhitao; Author
主题： Re: [DataCanvasIO/HyperTS] 单变量时序预测报错问题 (Issue #78)
HyperTS中并没有hyperts\lib\logging_init.py 文件，目前怀疑您的环境存在冲突及不可预知的混乱，您可以创建一个干净的新环境，然后重新安装hyperts看是否还有上述问题。

**Comment by zhangxjohn** [comment]
`log_level=2`设置为为`log_level=info`。

**Comment by wuzhitao** [comment]
你好，
我已经取消了log_level参数设置（或者修改成log_level=logging.INFO）在VSCode中以非调试模式运行还是会在退出前报：Error in atexit._run_exitfuncs
另外我发现好像在调用 make_experiment 和 run 之后我再调用 print 就会报OSError: [WinError 6] 句柄无效
测试代码如下
from hyperts import make_experiment
from hyperts.datasets import load_fixed_univariate_forecast_dataset
from hypernets.utils import logging, isnotebook, load_module
from hyperts.toolbox import temporal_train_test_split

df = load_fixed_univariate_forecast_dataset()

train_data, test_data = temporal_train_test_split(df, test_size=30)

print(test_data.to_json()) # 这里可以正常显示

experiment = make_experiment(train_data=train_data.copy(),
                             task='univariate-forecast',
                             timestamp='ds',
                             max_trials=5,
                             log_level=logging.INFO
                             )
model = experiment.run()

print(test_data.to_json()) # 这里再调用就会报错：OSError: [WinError 6] 句柄无效

X_test, y_test = model.split_X_y(test_data.copy())

forecast = model.predict(X_test)

results = model.evaluate(y_true=y_test, y_pred=forecast)

model.plot(forecast=forecast, actual=test_data, interactive=False)


 
发件人： Xiaojing Zhang
发送时间： 2023-01-16 18:22
收件人： DataCanvasIO/HyperTS
抄送： wuzhitao; Author
主题： Re: [DataCanvasIO/HyperTS] 单变量时序预测报错问题 (Issue #78)
log_level=2设置为为log_level=info。

**Comment by wuzhitao** [comment]
我尝试用其他的多变量数据集（load_network_traffic）进行测试，可以正常运行，也不会出现“OSError: [WinError 6] 句柄无效”和“Error in atexit._run_exitfuncs:”的错误提示，我怀疑是否是多进程处理的问题？

**Comment by zhangxjohn** [comment]
我们查该错误提示有提到多进程的，到遗憾的是，到目前该问题在我们这里无法复现。怀疑也可能与系统或者环境有关，希望您将继续提供更多线索或者方案解决该问题，HyperTS 十分感谢您的贡献。---- 回复的原邮件 ***@***.***>发送日期2023年01月19日 21:45 ***@***.***> 抄送人Xiaojing ***@***.***>***@***.***>主题Re: [DataCanvasIO/HyperTS] 单变量时序预测报错问题 (Issue #78)

我尝试用其他的多变量数据集（load_network_traffic）进行测试，可以正常运行，也不会出现“OSError: [WinError 6] 句柄无效”和“Error in atexit._run_exitfuncs:”的错误提示，我怀疑是否是多进程处理的问题？



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/DataCanvasIO/HyperTS/issues/78#issuecomment-1397000499",

"url": "https://github.com/DataCanvasIO/HyperTS/issues/78#issuecomment-1397000499",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by wuzhitao** [comment]
能方便告知一下具体的测试或运行环境和相关安装python包的版本吗？谢谢

**Comment by zhangxjohn** [comment]
> 能方便告知一下具体的测试或运行环境和相关安装python包的版本吗？谢谢

按照你创建新环境的操作：
1）conda create -n hyperts python==3.8
2）conda activate hyperts
3）pip install hyperts
我再次创新了新环境并测试您所提供的代码：

```
from hyperts import make_experiment
from hyperts.datasets import load_fixed_univariate_forecast_dataset
from hypernets.utils import logging, isnotebook, load_module
from hyperts.toolbox import temporal_train_test_split

df = load_fixed_univariate_forecast_dataset()

train_data, test_data = temporal_train_test_split(df, test_size=30)

print(test_data.to_json()) # 这里可以正常显示

experiment = make_experiment(train_data=train_data.copy(),
                             task='univariate-forecast',
                             timestamp='ds',
                             max_trials=5,
                             log_level=logging.INFO
                             )
model = experiment.run()

print(test_data.to_json()) # 这里也可以正常显示

X_test, y_test = model.split_X_y(test_data.copy())

forecast = model.predict(X_test)

results = model.evaluate(y_true=y_test, y_pred=forecast)

model.plot(forecast=forecast, actual=test_data, interactive=False)
```
没有出现任何问题，我的新环境为：
```
Package               Version
--------------------- -----------
argon2-cffi           21.3.0
argon2-cffi-bindings  21.2.0
asttokens             2.2.1
attrs                 21.2.0
ax-platform           0.2.2
backcall              0.2.0
bcrypt                4.0.1
beautifulsoup4        4.11.1
bleach                5.0.1
botorch               0.5.1
certifi               2022.12.7
cffi                  1.15.1
charset-normalizer    3.0.1
click                 8.1.3
cloudpickle           2.2.1
cmdstanpy             1.1.0
contourpy             1.0.7
convertdate           2.4.0
cryptography          39.0.0
cycler                0.11.0
Cython                0.29.17
dask                  2023.1.1
decorator             5.1.1
defusedxml            0.7.1
Deprecated            1.2.13
distributed           2023.1.1
ephem                 4.1.4
executing             1.2.0
fastjsonschema        2.16.1
fbprophet             0.7
featuretools          1.21.0
filterpy              1.4.5
fonttools             4.38.0
fsspec                2023.1.0
HeapDict              1.0.1
hijri-converter       2.2.4
holidays              0.18
htmlmin               0.1.12
hypernets             0.2.5.7
hyperts               0.2.0
idna                  3.4
ImageHash             4.2.1
importlib-metadata    6.0.0
importlib-resources   5.10.2
ipython               8.9.0
ipython-genutils      0.2.0
ipywidgets            7.7.1
jedi                  0.18.2
Jinja2                3.1.2
joblib                1.2.0
jsonschema            4.9.0
jupyterlab-pygments   0.2.2
jupyterlab-widgets    1.1.1
kats                  0.1.0
kiwisolver            1.4.4
korean-lunar-calendar 0.3.1
lightgbm              3.3.5
llvmlite              0.39.1
locket                1.0.0
LunarCalendar         0.0.9
MarkupSafe            2.1.2
matplotlib            3.6.3
matplotlib-inline     0.1.6
missingno             0.5.1
mistune               0.8.4
msgpack               1.0.4
multimethod           1.8
nbclient              0.6.6
nbconvert             6.5.0
nbformat              5.4.0
numba                 0.56.4
numpy                 1.21.6
packaging             23.0
pandas                1.5.3
pandas-profiling      3.2.0
pandocfilters         1.5.0
paramiko              3.0.0
parso                 0.8.3
partd                 1.3.0
patsy                 0.5.3
pexpect               4.8.0
phik                  0.12.2
pickleshare           0.7.5
Pillow                9.4.0
pip                   22.3.1
pkgutil_resolve_name  1.3.10
prettytable           3.6.0
prometheus-client     0.14.1
prompt-toolkit        3.0.36
prophet               1.1.2
psutil                5.9.4
ptyprocess            0.7.0
pure-eval             0.2.2
pyarrow               11.0.0
pycparser             2.21
pydantic              1.9.1
Pygments              2.14.0
pymannkendall         1.4.2
PyMeeus               0.5.12
PyNaCl                1.5.0
pyparsing             3.0.9
pyrsistent            0.18.1
python-dateutil       2.8.2
pytz                  2022.7.1
PyWavelets            1.3.0
PyYAML                6.0
requests              2.28.2
scikit-learn          1.2.1
scipy                 1.10.0
seaborn               0.11.2
Send2Trash            1.8.0
setuptools            66.1.1
six                   1.16.0
sktime                0.15.1
sortedcontainers      2.4.0
soupsieve             2.3.2.post1
stack-data            0.6.2
statsmodels           0.13.5
tangled-up-in-unicode 0.2.0
tblib                 1.7.0
terminado             0.15.0
threadpoolctl         3.1.0
tinycss2              1.1.1
toolz                 0.12.0
tornado               6.2
tqdm                  4.64.1
traitlets             5.8.1
urllib3               1.26.14
visions               0.7.4
wcwidth               0.2.6
webencodings          0.5.1
wheel                 0.38.4
widgetsnbextension    3.6.1
woodwork              0.21.2
wrapt                 1.14.1
XlsxWriter            3.0.7
zict                  2.2.0
zipp                  3.12.0

```

也许您的设备的环境变量或者anaconda存在问题，或许您可以尝试换一个设备再试一试。

**Comment by wuzhitao** [comment]
你好，
首先感谢你的解答，我在两台不同 Windows 操作系统的机器上基于Anaconda3 又分别做了如下测试：
1）创建全新的测试虚拟环境：hyperts （python版本 3.8.0）
2）激活进入 hyperts 环境执行：python hyperts_test.py
3）激活进入 hyperts 环境执行：python hyperts_test.py > out.log
其中，两台机器的操作系统分别为 Windows 10 家庭中文版（21H2）和 Windows 11 家庭中文版（22H2），创建虚拟环境的基本调用均为：
conda create -n hyperts python==3.8
conda activate hyperts 
pip install hyperts 
测试代码为：hyperts_test.py
测试过程如下：
1、在 Win10 环境下 2）和 3）都能执行完成，但是在 2）情况下会出现多组 logging error 信息
09:29:02 - cmdstanpy - INFO - Chain [1] start processing
--- Logging error ---
09:29:03 - cmdstanpy - INFO - Chain [1] done processing
--- Logging error ---
09:29:04 - cmdstanpy - INFO - Chain [1] start processing
--- Logging error ---
09:29:04 - cmdstanpy - INFO - Chain [1] done processing
--- Logging error ---
09:29:09 - cmdstanpy - INFO - Chain [1] start processing
--- Logging error ---
09:29:11 - cmdstanpy - INFO - Chain [1] done processing
--- Logging error ---
09:29:11 - cmdstanpy - INFO - Chain [1] start processing
--- Logging error ---
09:29:12 - cmdstanpy - INFO - Chain [1] done processing
--- Logging error ---
在 3）情况下，无上述异常提示。重定位输出日志见 out(win10).log 附件所示
2、在 Win11 环境下 2）会多次提示如下错误信息后程序中止：
--- Logging error --- 
Traceback (most recent call last): 
File "D:\DevTools\anaconda3\envs\hyperts\lib\logging\__init__.py", line 1084, in emit 
stream.write(msg + self.terminator) 
OSError: [WinError 6] 句柄无效。 
Call stack: 
File "hyperts_test.py", line 18, in 
model = experiment.run() 
File "D:\DevTools\anaconda3\envs\hyperts\lib\site-packages\hyperts\framework\compete.py", line 1119, in run 
return super().run(**run_kwargs) 
File "D:\DevTools\anaconda3\envs\hyperts\lib\site-packages\hypernets\experiment\_experiment.py", line 90, in run 
model = self.train(self.hyper_model, self.X_train, self.y_train, self.X_test, X_eval=self.X_eval, 
File "D:\DevTools\anaconda3\envs\hyperts\lib\site-packages\hypernets\experiment\compete.py", line 1542, in train 
step.fit_transform(hyper_model, X_train, y_train, X_test=X_test, X_eval=X_eval, y_eval=y_eval, 
File "D:\DevTools\anaconda3\envs\hyperts\lib\site-packages\hypernets\experiment\compete.py", line 1225, in fit_transform 
estimator = self.build_estimator(hyper_model, X_train, y_train, X_test=X_test, X_eval=X_eval, y_eval=y_eval, 
File "D:\DevTools\anaconda3\envs\hyperts\lib\site-packages\hyperts\framework\compete.py", line 365, in build_estimator ensemble.fit(X_eval, y_eval) 
File "D:\DevTools\anaconda3\envs\hyperts\lib\site-packages\hyperts\utils\ensemble\_greedy.py", line 56, in fit 
est_predictions = self._X2predictions(X) 
File "D:\DevTools\anaconda3\envs\hyperts\lib\site-packages\hyperts\utils\ensemble\_greedy.py", line 139, in _X2predictions 
pred = self._estimator_predict(estimator, X) 
File "D:\DevTools\anaconda3\envs\hyperts\lib\site-packages\hypernets\tabular\ensemble\base_ensemble.py", line 34, in _estimator_predict 
pred = estimator.predict(X) 
File "D:\DevTools\anaconda3\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 281, in predict 
X_transformed = self.fit_transform_X(X) 
File "D:\DevTools\anaconda3\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 349, in fit_transform_X 
X_transformed = self.data_pipeline.fit_transform(X[col_transformed]) 
File "D:\DevTools\anaconda3\envs\hyperts\lib\site-packages\hypernets\tabular\dataframe_mapper.py", line 299, in fit_transform 
logger.debug(f'fit_transform {len(columns)} columns with:\n{transformers}') 
File "D:\DevTools\anaconda3\envs\hyperts\lib\site-packages\hypernets\utils\logging.py", line 148, in debug 
self.log(DEBUG, msg, *args, **kwargs) 
File "D:\DevTools\anaconda3\envs\hyperts\lib\site-packages\hypernets\utils\logging.py", line 132, in log 
super(CustomizedLogger, self).log(level, msg, *args, **kwargs) 
Message: "fit_transform 1 columns with:\nPipeline(steps=[('Module_TimeSeriesHyperTransformer_1',\n )])" 
Arguments: ()
在 3）情况下，无上述错误提示。重定位输出日志见 out(win11).log 附件所示
另：我这里的conda虚拟环境安装包导出 yml 文件，导出语句为：conda env export -n hyperts > hyperts.yml
可调用如下语句导入：conda env create -n hyperts-test -f hyperts.yml

希望能对问题检查有些帮助，谢谢！



 
发件人： Xiaojing Zhang
发送时间： 2023-01-30 13:59
收件人： DataCanvasIO/HyperTS
抄送： wuzhitao; Author
主题： Re: [DataCanvasIO/HyperTS] 单变量时序预测报错问题 (Issue #78)
能方便告知一下具体的测试或运行环境和相关安装python包的版本吗？谢谢
按照你创建新环境的操作：
1）conda create -n hyperts python==3.8
2）conda activate hyperts
3）pip install hyperts
我再次创新了新环境并测试您所提供的代码：
from hyperts import make_experiment
from hyperts.datasets import load_fixed_univariate_forecast_dataset
from hypernets.utils import logging, isnotebook, load_module
from hyperts.toolbox import temporal_train_test_split
df = load_fixed_univariate_forecast_dataset()
train_data, test_data = temporal_train_test_split(df, test_size=30)
print(test_data.to_json()) # 这里可以正常显示
experiment = make_experiment(train_data=train_data.copy(),
                             task='univariate-forecast',
                             timestamp='ds',
                             max_trials=5,
                             log_level=logging.INFO
                             )
model = experiment.run()
print(test_data.to_json()) # 这里也可以正常显示
X_test, y_test = model.split_X_y(test_data.copy())
forecast = model.predict(X_test)
results = model.evaluate(y_true=y_test, y_pred=forecast)
model.plot(forecast=forecast, actual=test_data, interactive=False)

没有出现任何问题，我的新环境为：
Package               Version
--------------------- -----------
argon2-cffi           21.3.0
argon2-cffi-bindings  21.2.0
asttokens             2.2.1
attrs                 21.2.0
ax-platform           0.2.2
backcall              0.2.0
bcrypt                4.0.1
beautifulsoup4        4.11.1
bleach                5.0.1
botorch               0.5.1
certifi               2022.12.7
cffi                  1.15.1
charset-normalizer    3.0.1
click                 8.1.3
cloudpickle           2.2.1
cmdstanpy             1.1.0
contourpy             1.0.7
convertdate           2.4.0
cryptography          39.0.0
cycler                0.11.0
Cython                0.29.17
dask                  2023.1.1
decorator             5.1.1
defusedxml            0.7.1
Deprecated            1.2.13
distributed           2023.1.1
ephem                 4.1.4
executing             1.2.0
fastjsonschema        2.16.1
fbprophet             0.7
featuretools          1.21.0
filterpy              1.4.5
fonttools             4.38.0
fsspec                2023.1.0
HeapDict              1.0.1
hijri-converter       2.2.4
holidays              0.18
htmlmin               0.1.12
hypernets             0.2.5.7
hyperts               0.2.0
idna                  3.4
ImageHash             4.2.1
importlib-metadata    6.0.0
importlib-resources   5.10.2
ipython               8.9.0
ipython-genutils      0.2.0
ipywidgets            7.7.1
jedi                  0.18.2
Jinja2                3.1.2
joblib                1.2.0
jsonschema            4.9.0
jupyterlab-pygments   0.2.2
jupyterlab-widgets    1.1.1
kats                  0.1.0
kiwisolver            1.4.4
korean-lunar-calendar 0.3.1
lightgbm              3.3.5
llvmlite              0.39.1
locket                1.0.0
LunarCalendar         0.0.9
MarkupSafe            2.1.2
matplotlib            3.6.3
matplotlib-inline     0.1.6
missingno             0.5.1
mistune               0.8.4
msgpack               1.0.4
multimethod           1.8
nbclient              0.6.6
nbconvert             6.5.0
nbformat              5.4.0
numba                 0.56.4
numpy                 1.21.6
packaging             23.0
pandas                1.5.3
pandas-profiling      3.2.0
pandocfilters         1.5.0
paramiko              3.0.0
parso                 0.8.3
partd                 1.3.0
patsy                 0.5.3
pexpect               4.8.0
phik                  0.12.2
pickleshare           0.7.5
Pillow                9.4.0
pip                   22.3.1
pkgutil_resolve_name  1.3.10
prettytable           3.6.0
prometheus-client     0.14.1
prompt-toolkit        3.0.36
prophet               1.1.2
psutil                5.9.4
ptyprocess            0.7.0
pure-eval             0.2.2
pyarrow               11.0.0
pycparser             2.21
pydantic              1.9.1
Pygments              2.14.0
pymannkendall         1.4.2
PyMeeus               0.5.12
PyNaCl                1.5.0
pyparsing             3.0.9
pyrsistent            0.18.1
python-dateutil       2.8.2
pytz                  2022.7.1
PyWavelets            1.3.0
PyYAML                6.0
requests              2.28.2
scikit-learn          1.2.1
scipy                 1.10.0
seaborn               0.11.2
Send2Trash            1.8.0
setuptools            66.1.1
six                   1.16.0
sktime                0.15.1
sortedcontainers      2.4.0
soupsieve             2.3.2.post1
stack-data            0.6.2
statsmodels           0.13.5
tangled-up-in-unicode 0.2.0
tblib                 1.7.0
terminado             0.15.0
threadpoolctl         3.1.0
tinycss2              1.1.1
toolz                 0.12.0
tornado               6.2
tqdm                  4.64.1
traitlets             5.8.1
urllib3               1.26.14
visions               0.7.4
wcwidth               0.2.6
webencodings          0.5.1
wheel                 0.38.4
widgetsnbextension    3.6.1
woodwork              0.21.2
wrapt                 1.14.1
XlsxWriter            3.0.7
zict                  2.2.0
zipp                  3.12.0

也许您的设备的环境变量或者anaconda存在问题，或许您可以尝试换一个设备再试一试。
―

**Comment by zhangxjohn** [comment]
您好，我上次回答验证系统为Linux。

通过您提供的日志（`cmdstanpy - INFO - Chain [1] start processing`, 发现是prophet升级所导致的，但其为输出logging, 不会影响hyperts的建模结果）。为了避免其继续输出混淆视听，已经解决该问题。
您可更新代码`framework/wrappers/stats_wrappers.py`，目前已更新。

我已经在Win10系统验证，您所提的 2）已经顺利通过。

由于目前我这边没有Win11的设备，如果Win11仍有问题，建议您使用Win10或者Linux。
