### ISSUE TITLE
more information about build_input_head

### ISSUE THREAD

**Issue by 943fansi** [DataCanvasIO/HyperTS#82]
continuous_inputs, categorical_inputs = layers.build_input_head(window, continuous_columns, categorical_columns)

I want to use this function`.build_input_head`, but I don't know specific examples of continuous_columns and categorical_columns. I tried to use ```continuous_columns = ContinuousColumn(name='a', column_names=['a'], input_name='a')``` but got error `AttributeError: 'str' object has no attribute 'input_dim'`

**Comment by zhangxjohn** [comment]
Do you want to define a neural network model like the example https://github.com/DataCanvasIO/HyperTS/blob/main/examples/08_custom_search_space_02.ipynb?

**Comment by 943fansi** [comment]
@zhangxjohn Thanks for your reply. Yes, I am currently studying the code in `hyperts/framework/dl/models/deepar.py`.

**Comment by zhangxjohn** [comment]
Ok, if you want to understand `continuous_columns`, then I suggest that you can debug the code (Details in function `_preprocessor(self, X, y)` of [hyperts/framework/dl/_base.py](https://github.com/DataCanvasIO/HyperTS/blob/main/hyperts/framework/dl/_base.py)). This is a more efficient way.Moreover, if you want to define a new neural network model, just replace backbone in example [examples/08_custom_search_space_02.ipynb](https://github.com/DataCanvasIO/HyperTS/blob/main/examples/08_custom_search_space_02.ipynb).

**Comment by 943fansi** [comment]
Thank you for your suggestion, I am doing this. By the way, will the Transformer model or some updated models be added in the future? For example, from this repository [Time-Series-Library](https://github.com/thuml/Time-Series-Library).

**Comment by zhangxjohn** [comment]
Thank you for your suggestion, we are open to the idea. We also sincerely hope that you can contribute to the development of this project if you wish to do so.
