### ISSUE TITLE
版本介绍

### ISSUE THREAD

**Issue by wangjianqiao111** [DataCanvasIO/HyperTS#83]
你好，请问有版本介绍吗，stable和lasted的版本号分别是多少，官方推荐使用哪个版本的hyperts？

**Comment by zhangxjohn** [comment]
文档中有版本介绍，推荐使用0.2.0. https://hyperts.readthedocs.io/en/latest/contents/0800_release_note.html

**Comment by wangjianqiao111** [comment]
好的，谢谢
