### ISSUE TITLE
参数解释

### ISSUE THREAD

**Issue by wangjianqiao111** [DataCanvasIO/HyperTS#84]
contamination : float, should be in the interval (0, 1], optional (default=0.05).
        This parameter is adopted only in anomaly detection task to generate pseudo ground truth.
        The amount of contamination of the data set, i.e. the proportion
        of outliers in the data set. Used when fitting to define the threshold
        on the scores of the samples.

请问可以解释下contamination这个参数的具体含义吗，以及如何在异常检测中发挥作用，谢谢

**Comment by zhangxjohn** [comment]
HyperTS在异常检测中会应用含有伪标签的验证数据指导自动化建模过程。其中，contamination是一个生成伪标签的置信阈值。例如`contamination=0.05`表示为95%的置信度认为某个点为异常值。

**Comment by wangjianqiao111** [comment]
好的，谢谢
