### ISSUE TITLE
stat模式和dl模式都不支持时间序列回归和分类吗？如果是，那什么模式可以做回归和分类？

### ISSUE THREAD

**Issue by wangjianqiao111** [DataCanvasIO/HyperTS#88]
from hyperts import make_experiment
experiment = make_experiment(train_data=train_data.copy(),
mode='dl',
task='regression',
max_trials=5,
target='y',
searcher='random',
contamination=0.1)
# covariables=['HourSin', 'WeekCos', 'CBWD'])
model = experiment.run()
Traceback (most recent call last):
File "/Applications/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "", line 8, in
contamination=0.1)
File "/Applications/anaconda3/lib/python3.7/site-packages/hyperts/experiment.py", line 530, in make_experiment
metrics=reward_metric, covariates=autual_covariates)
File "/Applications/anaconda3/lib/python3.7/site-packages/hyperts/experiment.py", line 239, in default_search_space
'DLRegressionSearchSpace is not implemented yet.'
NotImplementedError: DLRegressionSearchSpace is not implemented yet.

dl模式也不支持回归吗？如果是那什么模式可以做回归和分类呢，还是不支持回归和分类任务

**Comment by zhangxjohn** [comment]
您好，感谢您的使用。
1、DL模式从0.1.3版本开始，已经稳定支持时序回归任务（目前为止，STATS模式不支持回归任务）。此外，时序分类任务DL、STATS模式所有版本均支持，对于所有版本的任务支持情况，在文档中的每个版本的Release Note均有阐明（Overview也可以查看），可以参阅Docs。
2、从你的报错信息看，我们这边查阅了您目前的版本疑似小于等于0.1.2.1，建议升级0.2.0。
3、对于回归任务，数据格式请参考Data Farmat(Docs与Examples)均可参看，只需将离散标签替换为连续标签即可。
4、如果其他问题，可先对应Docs自查并提供更多关键信息（如版本，版本冲突、数据格式，传参错误等）。

**Comment by zhangxjohn** [comment]
您好，感谢您的使用。

1、从报错信息`NotImplementedError: DLRegressionSearchSpace is not implemented yet.`，我们怀疑您目前使用的是`hyperts==0.1.2.1`版本，如果需要做时序回归任务，请更新版本大于`0.1.3`（建议更新至`0.2.0`）。
2、`0.1.3`版本后，DL与NAS版本均支持回归任务，目前为止，STATS模式不支持回归任务。
3、对于分类任务，`0.1.3`版本前支持的模式有STATS与DL版本，之后版本增加了NAS模式。
4、对于回归任务，其数据格式可参考DataFormat中的分类任务数据格式（需将label由离散型转换为连续型）。
5、更多说明可关注`Examples`与`Docs`。
