### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_pipeline_params'

### ISSUE THREAD

**Issue by kelvin-ksl** [DataCanvasIO/HyperTS#93]
how solve it?

**Comment by zhangxjohn** [comment]
Do you use  `model.get_pipeline_params()` or `model.get_pipeline_params` ?

**Comment by kelvin-ksl** [comment]
I used model.get_pipeline_params(). 

I ran print(model) and it returned 0, I don't understand why it's not getting the value in experiment.run()

**Comment by zhangxjohn** [comment]
Did you run `experiment.run()` successfully?
