### ISSUE TITLE
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### ISSUE THREAD

**Issue by kelvin-ksl** [DataCanvasIO/HyperTS#94]
05-04 20:09:07 E hypernets.e._experiment.py 106 - ExperimentID:[HyperTS_de1045f0eeffff25abcbae84d1758aed] - None: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''.

How resolve?

**Comment by zhangxjohn** [comment]
I can not understand your descirption. Can you give me more detials?

**Comment by kelvin-ksl** [comment]
I'm using 2 datasets, one for training and the other for testing, I follow example 14 (anomaly_detection_experiment) but in the temporal_train_test_split section I put the following syntax:

train_data = train_user2
test_data = df

other than that the code is identical to the example

*Error occurs in make_experiment

**Comment by zhangxjohn** [comment]
Ok, please first check the data format of  `train_data `and `test_data ` , `'anomaly' `should not in their columns. In addition, what is the  `train_user2`?

**Comment by zhangxjohn** [comment]
If you do not fix the code in the section `temporal_train_test_split`, any` Error` occurs?

**Comment by kelvin-ksl** [comment]
I'm assigning the anomaly column to the ground_truth variable as shown in the example.

train_user2 is my training data, in it I didn't remove the anomaly column.

**Comment by kelvin-ksl** [comment]
no error occurs before , only in the make experience section.

If you wish, I can share the notebook with the data I am using, I will only ask for your email to send it.

**Comment by zhangxjohn** [comment]
I am open, you can.

**Comment by kelvin-ksl** [comment]
sent.

**Comment by zhangxjohn** [comment]
Attention, my email is: `zhangxjohn@yeah.net`
