### ISSUE TITLE
how to use two datasets in hyperts

### ISSUE THREAD

**Issue by kelvin-ksl** [DataCanvasIO/HyperTS#97]
How to use 2 dataframes in hyperts? I'm trying to use a dataframe for training and another for testing, but I'm having problems. Concatting the dataframes and then splitting is not an option.

**Comment by zhangxjohn** [comment]
In `make_experimanet` to create a experiment, then you can feed the training data. After ` run`  the experiment, you can predict the test data using the ` model` which are obtained from `experiment.run()`. The process is similar to 'fit'(for training dataset) and 'predict'(for test dataset) in sklearn. Why do you want to use 2 dataframes? And where should they be used?

**Comment by kelvin-ksl** [comment]
I am making an algorithm for anomaly detection and want to train it with normal data only and then test it with anomalous data.
