### ISSUE TITLE
Need at least 3 dates to infer frequency

### ISSUE THREAD

**Issue by hello-the-vsworld** [DataCanvasIO/HyperTS#99]
我是用pandas导入了excel的表格数据，导入了时间，但建立实验就告诉我**至少需要3个日期来推断频率**，使用数据库里面的数据就不会报这个错误，我猜测是我哪里没有设置对，但我还是没有找到问题，希望有人能指出来。放上图片了。
![问题1](https://github.com/DataCanvasIO/HyperTS/assets/87103020/1ac15a80-beb6-409d-be4e-243808125bdc)
![问题2](https://github.com/DataCanvasIO/HyperTS/assets/87103020/4dff0bbe-67d7-4340-897d-082cf04a7d4d)

**Comment by zhangxjohn** [comment]
你好，从你的图片看，你的数据的频率太小了，因此无法推断出正确的freq。你可以将参数freq设置成`freq='null'`，此时，mode不要使用`stats`。这样应该可以解决你的问题。

**Comment by zhangxjohn** [comment]
你好，你可以将你的数据和代码给我一个demo吗？我复现一下你的问题。

**Comment by zhangxjohn** [comment]
我看到你的数据的频率是毫秒的（L），但是发现你的 `报错信息里好像设置了‘S’，如果设置了‘S’，那么该数据就没有频率了。你可以尝试`freq=‘L’，freq=None`或者`freq='null'`&`mode='dl'`,等，看看问题是否可以解决，如果无法解决，如不涉及信息泄露，您可以将你的数据（少量）和代码给我一个demo，我复现一下你的问题。此外，max_trails设置特别大很耗时，建议减少搜索的轮数。

**Comment by hello-the-vsworld** [comment]
感谢您的回复，很及时，下午我复现一下，届时将数据和代码给您发送一份。&nbsp;


无聊来读书
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaojing ***@***.***&gt;; 
发送时间: 2023年6月5日(星期一) 上午10:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DataCanvasIO/HyperTS] Need at least 3 dates to infer frequency (Issue #99)





 
你好，你可以将你的数据和代码给我一个demo吗？我复现一下你的问题。

**Comment by hello-the-vsworld** [comment]
max_trails=1000是否意味着最大训练次数为1000epoch，我的目的是想让算法模型尽可能多的训练，而不是训练10次或者较少的次数，担心结果不好。
&nbsp;


无聊来读书
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaojing ***@***.***&gt;; 
发送时间: 2023年6月5日(星期一) 上午10:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DataCanvasIO/HyperTS] Need at least 3 dates to infer frequency (Issue #99)





 
我看到你的数据的频率是毫秒的（L），但是发现你的 报错信息里好像设置了‘S’，如果设置了‘S’，那么该数据就没有频率了。你可以尝试freq=‘L’，freq=None或者freq='null'&amp;mode='dl'`,等，看看问题是否可以解决，如果无法解决，如不涉及信息泄露，您可以将你的数据（少量）和代码给我一个demo，我复现一下你的问题。此外，max_trails设置特别大很耗时，建议减少搜索的轮数。

**Comment by zhangxjohn** [comment]
max_trails=1000的意思是进行了1000次试验，换言之，搜索了1000种模型，不是1000个epoch，如果再考虑上epoch,那就是max_trials*epochs了。

**Comment by hello-the-vsworld** [comment]
https://colab.research.google.com/drive/17Zrlxg6jIgHuOxk-QYIgXEsVpjN9B2kf?usp=sharing
附件有代码和数据，另外粘贴了Colab的代码地址




无聊来读书
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DataCanvasIO/HyperTS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月5日(星期一) 中午1:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DataCanvasIO/HyperTS] Need at least 3 dates to infer frequency (Issue #99)





 
max_trails=1000的意思是进行了1000次试验，换言之，搜索了1000种模型，不是1000个epoch，如果再考虑上epoch,那就是max_trials*epochs了。

**Comment by zhangxjohn** [comment]
Colab无法访问， “`附件有代码和数据`”这个是发到我的邮箱了吗？

**Comment by hello-the-vsworld** [comment]
对的，发送到了邮箱的附件里




无聊来读书
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DataCanvasIO/HyperTS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月5日(星期一) 下午2:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DataCanvasIO/HyperTS] Need at least 3 dates to infer frequency (Issue #99)





 
Colab无法访问， “附件有代码和数据”这个是发到我的邮箱了吗？

**Comment by hello-the-vsworld** [comment]
https://colab.research.google.com/drive/17Zrlxg6jIgHuOxk-QYIgXEsVpjN9B2kf?usp=sharing




无聊来读书
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DataCanvasIO/HyperTS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月5日(星期一) 下午2:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DataCanvasIO/HyperTS] Need at least 3 dates to infer frequency (Issue #99)





 
Colab无法访问， “附件有代码和数据”这个是发到我的邮箱了吗？

**Comment by zhangxjohn** [comment]
我好像是没有收到，我是这个邮箱zhangxjohn@yeah.net哈

**Comment by zhangxjohn** [comment]
对于该问题，你可以通过将`timestamp_format='%Y-%m-%d %H:%M:%S.%f'`，解决该问题，建议采用最新代码，则可以忽略该设置。

**Comment by hello-the-vsworld** [comment]
感谢您的回复，这对我帮助很大！！！！！！！！！




无聊来读书
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DataCanvasIO/HyperTS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月6日(星期二) 上午10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DataCanvasIO/HyperTS] Need at least 3 dates to infer frequency (Issue #99)





 
对于该问题，你可以通过将timestamp_format='%Y-%m-%d %H:%M:%S.%f'，解决该问题，建议采用最新代码，则可以忽略该设置。
